name: Build golang app

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.x'
      - run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/hello
          ls -la build
      - uses: softprops/action-gh-release@v2
        with:
          files: build/*