name: Build golang app

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.x'
      - run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/hello
          ls -la build
  release-please-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          skip-github-pull-request: true
  release-please-pr:
    runs-on: ubuntu-latest
    needs:
      - build
      - release-please-release
    steps:
      - id: release-pr
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          skip-github-release: true