name: Build golang app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.x'
      - run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/hello
          ls -la build